# ── Include ModSecurity recommended config ───────────
Include /opt/ModSecurity/modsecurity.conf-recommended

# ── Override engine mode ──────────────────────────────
# On = block | DetectionOnly = chỉ log
SecRuleEngine On

# ── Request Body ─────────────────────────────────────
SecRequestBodyAccess On
SecRequestBodyLimit 13107200
SecRequestBodyNoFilesLimit 131072
SecRequestBodyLimitAction Reject

# ── Response Body ────────────────────────────────────
SecResponseBodyAccess On
SecResponseBodyLimit 524288
SecResponseBodyLimitAction ProcessPartial

# ── Audit Log ────────────────────────────────────────
SecAuditEngine RelevantOnly
SecAuditLog /var/log/modsec/audit.log
SecAuditLogFormat JSON
SecAuditLogParts ABIJDEFHZ
SecAuditLogRelevantStatus "^(?:5|4(?!04))"

# ── Debug (0=off, 9=max) ─────────────────────────────
SecDebugLog /var/log/modsec/debug.log
SecDebugLogLevel 0

# ── Data directories ─────────────────────────────────
SecTmpDir /tmp/modsecurity
SecDataDir /tmp/modsecurity
SecUploadDir /tmp/modsecurity
SecUploadKeepFiles Off

# ── Unicode map ──────────────────────────────────────
SecUnicodeMapFile /opt/ModSecurity/unicode.mapping 20127

# ── Include CRS ──────────────────────────────────────
Include /etc/nginx/modsecurity-crs/crs-setup.conf
Include /etc/nginx/modsecurity-crs/rules/*.conf
Include /etc/nginx/modsecurity-crs/rules/custom-rules.conf
